export const INTERVIEW_CATEGORIES = [
  { value: 'PRODUCT_SENSE', label: 'Product Sense', description: 'Design, user empathy, product thinking', icon: '🎯' },
  { value: 'EXECUTION', label: 'Execution', description: 'Metrics, prioritization, trade-offs', icon: '⚡' },
  { value: 'STRATEGY', label: 'Strategy', description: 'Market analysis, roadmap, competition', icon: '🗺️' },
  { value: 'BEHAVIORAL', label: 'Behavioral', description: 'Leadership, conflict, teamwork stories', icon: '🤝' },
  { value: 'ESTIMATION', label: 'Estimation', description: 'Market sizing, back-of-envelope', icon: '📊' },
  { value: 'METRICS', label: 'Metrics', description: 'Success metrics, KPIs, North Star', icon: '📈' },
  { value: 'PRODUCT_DESIGN', label: 'Product Design', description: 'UX, feature design, user flows', icon: '✏️' },
  { value: 'TECHNICAL_AI', label: 'Technical AI', description: 'AI/ML concepts, system design', icon: '🤖' },
  { value: 'ML_SYSTEM_DESIGN', label: 'ML System Design', description: 'ML pipelines, model architecture', icon: '⚙️' },
  { value: 'AI_ETHICS', label: 'AI Ethics', description: 'Fairness, safety, responsible AI', icon: '⚖️' },
] as const

export const DIFFICULTY_LEVELS = [
  { value: 'EASY', label: 'Easy', description: 'Foundational concepts, clear structure', color: 'text-emerald-600' },
  { value: 'MEDIUM', label: 'Medium', description: 'Realistic PM interview scenarios', color: 'text-amber-600' },
  { value: 'HARD', label: 'Hard', description: 'Tough follow-ups, ambiguous problems', color: 'text-orange-600' },
  { value: 'FAANG_LEVEL', label: 'FAANG Level', description: 'Top-tier company intensity', color: 'text-red-600' },
] as const

export const BEHAVIORAL_THEMES = [
  { value: 'LEADERSHIP', label: 'Leadership' },
  { value: 'CONFLICT_RESOLUTION', label: 'Conflict Resolution' },
  { value: 'FAILURE_AND_LEARNING', label: 'Failure & Learning' },
  { value: 'DATA_DRIVEN_DECISION', label: 'Data-Driven Decision' },
  { value: 'AMBIGUITY', label: 'Dealing with Ambiguity' },
  { value: 'CROSS_FUNCTIONAL', label: 'Cross-Functional Work' },
  { value: 'CUSTOMER_OBSESSION', label: 'Customer Obsession' },
  { value: 'INNOVATION', label: 'Innovation' },
  { value: 'PRIORITIZATION', label: 'Prioritization' },
  { value: 'INFLUENCE_WITHOUT_AUTHORITY', label: 'Influence Without Authority' },
  { value: 'TECHNICAL_DEPTH', label: 'Technical Depth' },
  { value: 'STAKEHOLDER_MANAGEMENT', label: 'Stakeholder Management' },
] as const

export const TEARDOWN_MODES = [
  { value: 'IMPROVE_FEATURE', label: 'Improve a Feature', description: 'How would you improve an existing feature?' },
  { value: 'DEFINE_NORTH_STAR', label: 'Define North Star', description: 'What should be the North Star metric?' },
  { value: 'PRIORITIZE_ROADMAP', label: 'Prioritize Roadmap', description: 'Given 5 features, prioritize and explain' },
  { value: 'DESIGN_V2', label: 'Design the V2', description: 'Design the next major version' },
  { value: 'COMPETITIVE_ANALYSIS', label: 'Competitive Analysis', description: 'How should they respond to competition?' },
  { value: 'DEFINE_METRICS', label: 'Define Metrics', description: 'Define a full metrics framework' },
] as const

export const COMPANY_LIST = [
  { name: 'Google', tier: 'FAANG' },
  { name: 'Meta', tier: 'FAANG' },
  { name: 'Apple', tier: 'FAANG' },
  { name: 'Amazon', tier: 'FAANG' },
  { name: 'Netflix', tier: 'FAANG' },
  { name: 'Microsoft', tier: 'BIG_TECH' },
  { name: 'Salesforce', tier: 'BIG_TECH' },
  { name: 'Oracle', tier: 'BIG_TECH' },
  { name: 'Adobe', tier: 'BIG_TECH' },
  { name: 'Intuit', tier: 'BIG_TECH' },
  { name: 'Uber', tier: 'BIG_TECH' },
  { name: 'Airbnb', tier: 'BIG_TECH' },
  { name: 'Stripe', tier: 'BIG_TECH' },
  { name: 'Lyft', tier: 'BIG_TECH' },
  { name: 'Twitter/X', tier: 'BIG_TECH' },
  { name: 'Snap', tier: 'BIG_TECH' },
  { name: 'Pinterest', tier: 'BIG_TECH' },
  { name: 'LinkedIn', tier: 'BIG_TECH' },
  { name: 'Dropbox', tier: 'BIG_TECH' },
  { name: 'Slack', tier: 'BIG_TECH' },
  { name: 'Shopify', tier: 'MID_STAGE' },
  { name: 'Notion', tier: 'MID_STAGE' },
  { name: 'Figma', tier: 'MID_STAGE' },
  { name: 'Canva', tier: 'MID_STAGE' },
  { name: 'Duolingo', tier: 'MID_STAGE' },
  { name: 'Coinbase', tier: 'MID_STAGE' },
  { name: 'Robinhood', tier: 'MID_STAGE' },
  { name: 'DoorDash', tier: 'MID_STAGE' },
  { name: 'Instacart', tier: 'MID_STAGE' },
  { name: 'Roblox', tier: 'MID_STAGE' },
  { name: 'Discord', tier: 'MID_STAGE' },
  { name: 'Plaid', tier: 'MID_STAGE' },
  { name: 'Databricks', tier: 'MID_STAGE' },
  { name: 'Snowflake', tier: 'MID_STAGE' },
  { name: 'Confluent', tier: 'MID_STAGE' },
  { name: 'OpenAI', tier: 'MID_STAGE' },
  { name: 'Anthropic', tier: 'MID_STAGE' },
  { name: 'Scale AI', tier: 'MID_STAGE' },
  { name: 'Hugging Face', tier: 'STARTUP' },
  { name: 'Cohere', tier: 'STARTUP' },
  { name: 'Mistral', tier: 'STARTUP' },
  { name: 'Character.AI', tier: 'STARTUP' },
  { name: 'Perplexity', tier: 'STARTUP' },
  { name: 'Brex', tier: 'STARTUP' },
  { name: 'Rippling', tier: 'MID_STAGE' },
  { name: 'Gusto', tier: 'MID_STAGE' },
  { name: 'Carta', tier: 'MID_STAGE' },
  { name: 'Lattice', tier: 'STARTUP' },
  { name: 'Asana', tier: 'BIG_TECH' },
  { name: 'Monday.com', tier: 'MID_STAGE' },
  { name: 'HubSpot', tier: 'BIG_TECH' },
  { name: 'Zendesk', tier: 'BIG_TECH' },
  { name: 'Twilio', tier: 'BIG_TECH' },
] as const

export const FRAMEWORKS_DATA = {
  prioritization: [
    {
      slug: 'rice',
      title: 'RICE Framework',
      category: 'Prioritization',
      summary: 'Reach, Impact, Confidence, Effort — a structured scoring method for feature prioritization.',
    },
    {
      slug: 'moscow',
      title: 'MoSCoW Method',
      category: 'Prioritization',
      summary: 'Must have, Should have, Could have, Won\'t have — categorizes requirements by priority.',
    },
    {
      slug: 'kano',
      title: 'Kano Model',
      category: 'Prioritization',
      summary: 'Categorizes features by user satisfaction: Basic, Performance, and Delight.',
    },
    {
      slug: 'ice',
      title: 'ICE Scoring',
      category: 'Prioritization',
      summary: 'Impact, Confidence, Ease — a lightweight prioritization framework for fast decisions.',
    },
  ],
  metrics: [
    {
      slug: 'aarrr',
      title: 'AARRR (Pirate Metrics)',
      category: 'Metrics',
      summary: 'Acquisition, Activation, Retention, Revenue, Referral — the full funnel.',
    },
    {
      slug: 'heart',
      title: 'HEART Framework',
      category: 'Metrics',
      summary: 'Happiness, Engagement, Adoption, Retention, Task Success — user-centered metrics.',
    },
    {
      slug: 'north-star',
      title: 'North Star Framework',
      category: 'Metrics',
      summary: 'A single metric that best captures the core value your product delivers.',
    },
    {
      slug: 'okrs',
      title: 'OKRs',
      category: 'Metrics',
      summary: 'Objectives and Key Results — aligning teams around measurable outcomes.',
    },
  ],
  strategy: [
    {
      slug: 'jobs-to-be-done',
      title: 'Jobs-to-be-Done',
      category: 'Product Strategy',
      summary: 'Users "hire" products to do a job. Focus on the job, not the user.',
    },
    {
      slug: 'blue-ocean',
      title: 'Blue Ocean Strategy',
      category: 'Product Strategy',
      summary: 'Create uncontested market space rather than competing in existing markets.',
    },
    {
      slug: 'porters-five-forces',
      title: "Porter's Five Forces",
      category: 'Product Strategy',
      summary: 'Analyze competitive forces: suppliers, buyers, substitutes, new entrants, rivalry.',
    },
    {
      slug: 'tam-sam-som',
      title: 'TAM/SAM/SOM',
      category: 'Product Strategy',
      summary: 'Total Addressable Market, Serviceable Addressable Market, Serviceable Obtainable Market.',
    },
  ],
  communication: [
    {
      slug: 'star',
      title: 'STAR Method',
      category: 'Communication',
      summary: 'Situation, Task, Action, Result — the gold standard for behavioral interview answers.',
    },
    {
      slug: 'circles',
      title: 'CIRCLES Method',
      category: 'Communication',
      summary: 'Comprehend, Identify, Report, Cut, List, Evaluate, Summarize — for product design questions.',
    },
    {
      slug: 'mece',
      title: 'MECE Principle',
      category: 'Communication',
      summary: 'Mutually Exclusive, Collectively Exhaustive — structuring problems without gaps or overlaps.',
    },
  ],
  aipm: [
    {
      slug: 'transformers-for-pms',
      title: 'Transformers for PMs',
      category: 'AI-PM Concepts',
      summary: 'How transformer architecture works and why it matters for product decisions.',
    },
    {
      slug: 'rag',
      title: 'RAG (Retrieval-Augmented Generation)',
      category: 'AI-PM Concepts',
      summary: 'How RAG improves AI accuracy and why PMs need to understand it.',
    },
    {
      slug: 'precision-recall',
      title: 'Precision vs Recall',
      category: 'AI-PM Concepts',
      summary: 'When false positives vs false negatives matter more for product decisions.',
    },
    {
      slug: 'build-vs-buy-ai',
      title: 'Build vs Buy for AI',
      category: 'AI-PM Concepts',
      summary: 'Framework for deciding when to build custom AI vs use existing models.',
    },
    {
      slug: 'ai-ethics-frameworks',
      title: 'AI Ethics Frameworks',
      category: 'AI-PM Concepts',
      summary: 'Fairness, Transparency, Accountability — practical ethics for AI PMs.',
    },
    {
      slug: 'latency-accuracy-tradeoff',
      title: 'Latency vs Accuracy Tradeoffs',
      category: 'AI-PM Concepts',
      summary: 'How to think about speed vs quality tradeoffs in AI product decisions.',
    },
    {
      slug: 'fine-tuning-vs-foundation',
      title: 'Foundation Models vs Fine-tuning',
      category: 'AI-PM Concepts',
      summary: 'When to use a foundation model vs fine-tune for your specific use case.',
    },
  ],
}

export const PRODUCTS_FOR_TEARDOWN = [
  { name: 'Spotify', category: 'Music & Audio', icon: '🎵' },
  { name: 'Uber', category: 'Transportation', icon: '🚗' },
  { name: 'Instagram', category: 'Social Media', icon: '📸' },
  { name: 'ChatGPT', category: 'AI', icon: '🤖' },
  { name: 'Notion', category: 'Productivity', icon: '📝' },
  { name: 'Airbnb', category: 'Travel', icon: '🏠' },
  { name: 'Netflix', category: 'Entertainment', icon: '🎬' },
  { name: 'DoorDash', category: 'Food Delivery', icon: '🍔' },
  { name: 'Slack', category: 'Communication', icon: '💬' },
  { name: 'Google Maps', category: 'Navigation', icon: '🗺️' },
  { name: 'TikTok', category: 'Social Media', icon: '🎵' },
  { name: 'LinkedIn', category: 'Professional Network', icon: '💼' },
  { name: 'Duolingo', category: 'Education', icon: '🦜' },
  { name: 'Figma', category: 'Design', icon: '✏️' },
  { name: 'Discord', category: 'Gaming & Community', icon: '🎮' },
  { name: 'Stripe', category: 'Payments', icon: '💳' },
] as const

export const WEAK_AREA_OPTIONS = [
  'Product Sense',
  'Metrics',
  'Estimation',
  'Behavioral',
  'Strategy',
  'Execution',
  'Technical/AI',
  'Communication',
  'Structuring Answers',
  'Following Up',
]

export const INTERVIEW_ROUND_OPTIONS = [
  'Phone Screen',
  'Recruiter Call',
  'Technical Screen',
  'Behavioral Round',
  'Onsite Round 1',
  'Onsite Round 2',
  'Onsite Round 3',
  'Final Round',
  'Case Study',
  'Presentation',
  'Other',
]
